version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"


  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

